name: Deploy Website

on: [push]

jobs:
  build:	
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      	 run: cd ./proj1/my-app
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      # Install npm packages
      - name: Install packages
        run: npm update
      - name: Build the app
        run: npm run-script build
      - run: npm install -g surge
      - run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
